name: elevar_fitness_tracker
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0

  path: any

  cupertino_icons: ^1.0.2

  loading_animation_widget: ^1.2.0+4

  firebase_core: ^2.21.0

  cloud_firestore: ^4.12.2

<<<<<<< Updated upstream
  pedometer: ^4.0.1
=======
  http: ^1.1.0

  flutter_typeahead: ^4.8.0
  pedometer: ^4.0.1
  flutter_local_notifications:
  
  pedometer: ^4.0.1
  
  flutter_local_notifications:
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_local_notifications:
  timezone:

  timezone:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
